version: "3.9"
services:
  #app:
  #  build: app
  #  ports:
  #    - 0.0.0.0:4567:8000
  #  environment:
  #    MYSQL_HOST: mysql
  #    MYSQL_USER: root
  #    MYSQL_PASSWORD: password
  #    MYSQL_DB: nextgenml
  #  depends_on:
  #    - mysql
  #    - chatgpt-backend
  #  volumes:
  #    - ./app/config/:/app/config/
  #    - ./app/config.js:/app/config.js
  #    - ./app/manager:/app/manager
  #    - ./app/script:/app/script
  #    - ./app/repository:/app/repository
  #    - ./app/package.json:/app/package.json
  #    - ./app/tmp:/app/tmp
  #    - ./app/uploads:/app/uploads
  #    - ./app/utils:/app/utils

  #mysql:
  #  image: mysql:5.7
  #  container_name: mysql
  #  environment:
  #    MYSQL_ROOT_PASSWORD: password
  #    MYSQL_DATABASE: nextgenml
  #  volumes:
  #    - mysql_volume:/var/lib/mysql

  prod-app:
    build: IOSite
    ports:
      - 0.0.0.0:5678:8000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: nextgenml
      NODE_ENV: 'production'
      NODE_OPTIONS: --max-old-space-size=8192
    depends_on:
      - prod-mysql
      - chatgpt-backend
    volumes:
      - ./IOSite/.env:/app/.env
      - ./IOSite/logs:/app/logs
      - ./IOSite/routes:/app/routes
      - ./IOSite/constants:/app/constants
      - ./IOSite/uploads:/app/uploads
      - ./IOSite/utils:/app/utils
      - ./IOSite/dbconnect.js:/app/dbconnect.js
      - ./IOSite/index.js:/app/index.js
      - ./IOSite/config.js:/app/config.js
      - ./IOSite/config:/app/config
      - ./IOSite/repository:/app/repository
      - ./IOSite/controllers:/app/controllers
      - ./IOSite/migrations:/app/migrations
      - ./IOSite/manager:/app/manager
      - ./IOSite/package.json:/app/package.json
      - ./IOSite/script:/app/script

  prod-mysql:
    image: mysql:5.7
    deploy: 
      resources:
        limits:
          memory: 12G
    container_name: prod-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nextgenml
    volumes:
      - prod_mysql_volume:/var/lib/mysql
    
  proxy:
    image: nginx:alpine
    restart: unless-stopped
    volumes: 
      - ./dns_config/nginx/conf/:/etc/nginx/conf.d/:ro
      - ./dns_config/certbot/www:/var/www/certbot/:ro
      - ./dns_config/certbot/conf/:/etc/letsencrypt/:rw
      - ./dns_config/nginx/error_page.html:/usr/share/nginx/html/error_page.html:ro
    ports:
      - 80:80 # listen for http connections
      - 443:443 # listen for https connections
    depends_on:
      - prod-app
      - chatgpt-backend
      - chatgpt-frontend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./dns_config/certbot/www/:/var/www/certbot/:rw
      - ./dns_config/certbot/conf/:/etc/letsencrypt/:rw

  chatgpt-backend:
    build: chatgpt_API
    volumes:
      - ./chatgpt_API/app.js:/app/app.js
      - ./chatgpt_API/utils.js:/app/utils.js
      - ./chatgpt_API/keys.json:/app/keys.json

  chatgpt-frontend:
    build: chatgpt_frontend
    depends_on:
      - chatgpt-backend
  
volumes:
  mysql_volume:
  prod_mysql_volume:
