version: "3.9"
services:
  prod-app:
    build: IOSite
    ports:
      - 0.0.0.0:5678:8000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: nextgenml
      NODE_ENV: 'production'
      NODE_OPTIONS: --max-old-space-size=8192
    depends_on:
      - prod-mysql
    volumes:
      - ./IOSite/.env:/app/.env
      - ./IOSite/logs:/app/logs
      - ./IOSite/routes:/app/routes
      - ./IOSite/constants:/app/constants
      - ./IOSite/uploads:/app/uploads
      - ./IOSite/utils:/app/utils
      - ./IOSite/dbconnect.js:/app/dbconnect.js
      - ./IOSite/index.js:/app/index.js
      - ./IOSite/config.js:/app/config.js
      - ./IOSite/config:/app/config
      - ./IOSite/repository:/app/repository
      - ./IOSite/controllers:/app/controllers
      - ./IOSite/migrations:/app/migrations
      - ./IOSite/manager:/app/manager
      - ./IOSite/package.json:/app/package.json
      - ./IOSite/script:/app/script

  prod-mysql:
    image: mysql:5.7
    deploy: 
      resources:
        limits:
          memory: 12G
    container_name: prod-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: nextgenml
    volumes:
      - prod_mysql_volume:/var/lib/mysql
    command: --max_allowed_packet=32505856
  
volumes:
  mysql_volume:
  prod_mysql_volume:
  inbox_mysql_volume:
